version: '3.8'

# Docker Compose Override for Local Development
# This file extends docker-compose.yml with development-specific settings

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: majestic-app-dev
    ports:
      - "3000:5000"  # Different port for development
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DEBUG=majestic:*
      - LOG_LEVEL=debug
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    depends_on:
      postgres:
        condition: service_healthy
    
  postgres:
    ports:
      - "5433:5432"  # Different port to avoid conflicts
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./scripts/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - ./tests/test-data:/docker-entrypoint-initdb.d/test-data:ro
    environment:
      - POSTGRES_DB=health_app_dev
      - POSTGRES_USER=majestic_dev
      - POSTGRES_PASSWORD=dev_password
    command: >
      postgres
        -c log_statement=all
        -c log_destination=stderr
        -c logging_collector=on
        -c log_directory=/var/log/postgresql
        -c log_min_duration_statement=0

volumes:
  postgres_dev_data:
    driver: local

networks:
  majestic_network:
    driver: bridge